name: tests

on:
    pull_request: # when a PR is opened or reopened
        types: [opened, reopened]
        branches:
            - main

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    standalone-test:
        uses: ./.github/workflows/standalone-test.yml
        with:
            metadata-matrix: '["zookeeper"]'
            db-matrix: '["Redis"]'
            os-matrix: '["macos-latest"]'
    standalone-test-no-optimizer:
        uses: ./.github/workflows/standalone-test-no-optimizer.yml
        with:
            metadata-matrix: '["zookeeper"]'
            db-matrix: '["Redis"]'
            os-matrix: '["macos-latest"]'
    analyze-required-test-check:
        if: always()
        needs: # List of jobs that must pass. Add more jobs if needed.
            - standalone-test
            - standalone-test-no-optimizer
        runs-on: ubuntu-latest
        steps:
            - name: Decide whether the needed jobs succeeded or failed
              uses: re-actors/alls-green@release/v1
              with:
                  jobs: ${{ toJSON(needs) }}
