name: tests

on:
    pull_request: # when a PR is opened or reopened
        types: [opened, reopened]
        branches:
            - main

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    cluster-test:
        uses: ./.github/workflows/cluster-test.yml
    analyze-required-test-check:
        if: always()
        needs: # List of jobs that must pass. Add more jobs if needed.
            - cluster-test
        runs-on: ubuntu-latest
        steps:
            - name: Decide whether the needed jobs succeeded or failed
              uses: re-actors/alls-green@release/v1
              with:
                  jobs: ${{ toJSON(needs) }}
